# Generated by Django 3.2.4 on 2021-06-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('cnic', models.CharField(max_length=200)),
                ('phone_no', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('experience', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(max_length=200)),
                ('current_city', models.CharField(max_length=200)),
            ],
        ),
    ]
