# Generated by Django 3.2.4 on 2021-06-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
